// <auto-generated />
using System;
using Ambulancia_MIS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ambulancia_MIS.Migrations
{
    [DbContext(typeof(AmbulanciaContext))]
    [Migration("20260505215712_a1")]
    partial class a1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ambulancia_MIS.Dominio.AlertaCritica", b =>
                {
                    b.Property<long>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdAlerta"));

                    b.Property<bool>("Atendida")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAlerta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gravedad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("IdMision")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAlerta");

                    b.ToTable("AlertasCriticas");
                });

            modelBuilder.Entity("Ambulancia_MIS.Dominio.Ambulancia", b =>
                {
                    b.Property<long>("IdAmbulancia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdAmbulancia"));

                    b.Property<int>("AnioFabricacion")
                        .HasColumnType("integer");

                    b.Property<int>("CapacidadOxigenoLitros")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TieneDesfibrilador")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAmbulancia");

                    b.ToTable("Ambulancias");

                    b.HasData(
                        new
                        {
                            IdAmbulancia = 1L,
                            AnioFabricacion = 2020,
                            CapacidadOxigenoLitros = 2000,
                            Codigo = "AMB-001",
                            Estado = "ACTIVO",
                            Kilometraje = 15000,
                            Marca = "FORD",
                            Modelo = "TRANSIT",
                            Placa = "1234ABC",
                            TieneDesfibrilador = true,
                            Tipo = "UCI_MOVIL"
                        },
                        new
                        {
                            IdAmbulancia = 2L,
                            AnioFabricacion = 2021,
                            CapacidadOxigenoLitros = 1000,
                            Codigo = "AMB-002",
                            Estado = "ACTIVO",
                            Kilometraje = 8000,
                            Marca = "MERCEDES",
                            Modelo = "SPRINTER",
                            Placa = "5678DEF",
                            TieneDesfibrilador = false,
                            Tipo = "BASICA"
                        });
                });

            modelBuilder.Entity("Ambulancia_MIS.Dominio.AmbulanciaInsumo", b =>
                {
                    b.Property<long>("IdAmbulancia")
                        .HasColumnType("bigint");

                    b.Property<long>("IdInsumo")
                        .HasColumnType("bigint");

                    b.Property<long?>("AmbulanciaIdAmbulancia")
                        .HasColumnType("bigint");

                    b.Property<int>("CantidadActual")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadMinima")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCaducidad")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUltimaReposicion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("InsumoIdInsumo")
                        .HasColumnType("bigint");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UbicacionAlmacen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAmbulancia", "IdInsumo");

                    b.HasIndex("AmbulanciaIdAmbulancia");

                    b.HasIndex("InsumoIdInsumo");

                    b.ToTable("AmbulanciaInsumos");

                    b.HasData(
                        new
                        {
                            IdAmbulancia = 1L,
                            IdInsumo = 1L,
                            CantidadActual = 10,
                            CantidadMinima = 5,
                            Estado = "ACTIVO",
                            FechaUltimaReposicion = new DateTime(2026, 5, 5, 21, 57, 4, 92, DateTimeKind.Utc).AddTicks(9161),
                            Lote = "LOTE-001",
                            UbicacionAlmacen = ""
                        },
                        new
                        {
                            IdAmbulancia = 1L,
                            IdInsumo = 2L,
                            CantidadActual = 2000,
                            CantidadMinima = 500,
                            Estado = "ACTIVO",
                            FechaUltimaReposicion = new DateTime(2026, 5, 5, 21, 57, 4, 92, DateTimeKind.Utc).AddTicks(9161),
                            Lote = "LOTE-002",
                            UbicacionAlmacen = ""
                        },
                        new
                        {
                            IdAmbulancia = 1L,
                            IdInsumo = 3L,
                            CantidadActual = 50,
                            CantidadMinima = 20,
                            Estado = "ACTIVO",
                            FechaUltimaReposicion = new DateTime(2026, 5, 5, 21, 57, 4, 92, DateTimeKind.Utc).AddTicks(9161),
                            Lote = "LOTE-003",
                            UbicacionAlmacen = ""
                        },
                        new
                        {
                            IdAmbulancia = 1L,
                            IdInsumo = 4L,
                            CantidadActual = 2,
                            CantidadMinima = 2,
                            Estado = "ACTIVO",
                            FechaUltimaReposicion = new DateTime(2026, 5, 5, 21, 57, 4, 92, DateTimeKind.Utc).AddTicks(9161),
                            Lote = "LOTE-004",
                            UbicacionAlmacen = ""
                        },
                        new
                        {
                            IdAmbulancia = 2L,
                            IdInsumo = 1L,
                            CantidadActual = 8,
                            CantidadMinima = 5,
                            Estado = "ACTIVO",
                            FechaUltimaReposicion = new DateTime(2026, 5, 5, 21, 57, 4, 92, DateTimeKind.Utc).AddTicks(9161),
                            Lote = "LOTE-005",
                            UbicacionAlmacen = ""
                        },
                        new
                        {
                            IdAmbulancia = 2L,
                            IdInsumo = 2L,
                            CantidadActual = 1500,
                            CantidadMinima = 500,
                            Estado = "ACTIVO",
                            FechaUltimaReposicion = new DateTime(2026, 5, 5, 21, 57, 4, 92, DateTimeKind.Utc).AddTicks(9161),
                            Lote = "LOTE-006",
                            UbicacionAlmacen = ""
                        },
                        new
                        {
                            IdAmbulancia = 2L,
                            IdInsumo = 3L,
                            CantidadActual = 45,
                            CantidadMinima = 20,
                            Estado = "ACTIVO",
                            FechaUltimaReposicion = new DateTime(2026, 5, 5, 21, 57, 4, 92, DateTimeKind.Utc).AddTicks(9161),
                            Lote = "LOTE-007",
                            UbicacionAlmacen = ""
                        });
                });

            modelBuilder.Entity("Ambulancia_MIS.Dominio.ConstanteVital", b =>
                {
                    b.Property<long>("IdConstante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdConstante"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FrecuenciaCardiaca")
                        .HasColumnType("integer");

                    b.Property<int>("FrecuenciaRespiratoria")
                        .HasColumnType("integer");

                    b.Property<int?>("Glasgow")
                        .HasColumnType("integer");

                    b.Property<long>("IdMision")
                        .HasColumnType("bigint");

                    b.Property<int>("PresionDiastolica")
                        .HasColumnType("integer");

                    b.Property<int>("PresionSistolica")
                        .HasColumnType("integer");

                    b.Property<int>("SaturacionOxigeno")
                        .HasColumnType("integer");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("numeric");

                    b.HasKey("IdConstante");

                    b.ToTable("ConstantesVitales");
                });

            modelBuilder.Entity("Ambulancia_MIS.Dominio.HistorialUbicacion", b =>
                {
                    b.Property<long>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdHistorial"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdAmbulancia")
                        .HasColumnType("bigint");

                    b.Property<long>("IdMision")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("numeric");

                    b.Property<int>("VelocidadKmh")
                        .HasColumnType("integer");

                    b.HasKey("IdHistorial");

                    b.ToTable("HistorialUbicaciones");
                });

            modelBuilder.Entity("Ambulancia_MIS.Dominio.Insumo", b =>
                {
                    b.Property<long>("IdInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdInsumo"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<bool>("RequiereRefrigeracion")
                        .HasColumnType("boolean");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdInsumo");

                    b.ToTable("Insumos");

                    b.HasData(
                        new
                        {
                            IdInsumo = 1L,
                            Categoria = "FARMACO",
                            Codigo = "INS-ADR-01",
                            Descripcion = "",
                            Estado = "ACTIVO",
                            Nombre = "ADRENALINA",
                            PrecioUnitario = 12.50m,
                            RequiereRefrigeracion = false,
                            StockMinimo = 5,
                            UnidadMedida = "AMPOLIA"
                        },
                        new
                        {
                            IdInsumo = 2L,
                            Categoria = "GAS",
                            Codigo = "INS-OXI-01",
                            Descripcion = "",
                            Estado = "ACTIVO",
                            Nombre = "OXIGENO",
                            PrecioUnitario = 5.00m,
                            RequiereRefrigeracion = false,
                            StockMinimo = 500,
                            UnidadMedida = "LITRO"
                        },
                        new
                        {
                            IdInsumo = 3L,
                            Categoria = "CURACION",
                            Codigo = "INS-GAS-01",
                            Descripcion = "",
                            Estado = "ACTIVO",
                            Nombre = "GASA ESTERIL",
                            PrecioUnitario = 0.50m,
                            RequiereRefrigeracion = false,
                            StockMinimo = 20,
                            UnidadMedida = "UNIDAD"
                        },
                        new
                        {
                            IdInsumo = 4L,
                            Categoria = "HEMODERIVADO",
                            Codigo = "INS-SAN-01",
                            Descripcion = "",
                            Estado = "ACTIVO",
                            Nombre = "SANGRE TIPO O+",
                            PrecioUnitario = 150.00m,
                            RequiereRefrigeracion = false,
                            StockMinimo = 2,
                            UnidadMedida = "UNIDAD"
                        });
                });

            modelBuilder.Entity("Ambulancia_MIS.Dominio.Mision", b =>
                {
                    b.Property<long>("IdMision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdMision"));

                    b.Property<decimal>("DistanciaKm")
                        .HasColumnType("numeric");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHoraLlamada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLlegadaHospital")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLlegadaPaciente")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LatDestino")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LatOrigen")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LngDestino")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LngOrigen")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroSolicitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TiempoRespuestaSegundos")
                        .HasColumnType("integer");

                    b.HasKey("IdMision");

                    b.HasIndex("NumeroSolicitud")
                        .IsUnique();

                    b.ToTable("Misiones");

                    b.HasData(
                        new
                        {
                            IdMision = 1L,
                            DistanciaKm = 5.2m,
                            Estado = "FINALIZADA",
                            FechaHoraLlamada = new DateTime(2026, 5, 5, 19, 57, 4, 92, DateTimeKind.Utc).AddTicks(9161),
                            LatDestino = -17.3845m,
                            LatOrigen = -17.3935m,
                            LngDestino = -66.1468m,
                            LngOrigen = -66.1570m,
                            NumeroSolicitud = "SOL-2025-001",
                            Observaciones = "PACIENTE CON PARO CARDIACO",
                            Prioridad = "ROJO",
                            TiempoRespuestaSegundos = 480
                        });
                });

            modelBuilder.Entity("Ambulancia_MIS.Dominio.Notificacion", b =>
                {
                    b.Property<long>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdNotificacion"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enviada")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdMision")
                        .HasColumnType("bigint");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdNotificacion");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Ambulancia_MIS.Dominio.PlantillaInsumo", b =>
                {
                    b.Property<long>("IdPlantilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdPlantilla"));

                    b.Property<int>("CantidadRequerida")
                        .HasColumnType("integer");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("boolean");

                    b.Property<long>("IdInsumo")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsumoIdInsumo")
                        .HasColumnType("bigint");

                    b.Property<int>("NivelCritico")
                        .HasColumnType("integer");

                    b.HasKey("IdPlantilla");

                    b.HasIndex("InsumoIdInsumo");

                    b.ToTable("PlantillaInsumos");

                    b.HasData(
                        new
                        {
                            IdPlantilla = 1L,
                            CantidadRequerida = 10,
                            EsObligatorio = true,
                            IdInsumo = 1L,
                            NivelCritico = 3
                        },
                        new
                        {
                            IdPlantilla = 2L,
                            CantidadRequerida = 2000,
                            EsObligatorio = true,
                            IdInsumo = 2L,
                            NivelCritico = 500
                        },
                        new
                        {
                            IdPlantilla = 3L,
                            CantidadRequerida = 50,
                            EsObligatorio = true,
                            IdInsumo = 3L,
                            NivelCritico = 10
                        },
                        new
                        {
                            IdPlantilla = 4L,
                            CantidadRequerida = 2,
                            EsObligatorio = true,
                            IdInsumo = 4L,
                            NivelCritico = 1
                        });
                });

            modelBuilder.Entity("Ambulancia_MIS.Dominio.AmbulanciaInsumo", b =>
                {
                    b.HasOne("Ambulancia_MIS.Dominio.Ambulancia", "Ambulancia")
                        .WithMany("AmbulanciaInsumos")
                        .HasForeignKey("AmbulanciaIdAmbulancia");

                    b.HasOne("Ambulancia_MIS.Dominio.Insumo", "Insumo")
                        .WithMany("AmbulanciaInsumos")
                        .HasForeignKey("InsumoIdInsumo");

                    b.Navigation("Ambulancia");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("Ambulancia_MIS.Dominio.PlantillaInsumo", b =>
                {
                    b.HasOne("Ambulancia_MIS.Dominio.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoIdInsumo");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("Ambulancia_MIS.Dominio.Ambulancia", b =>
                {
                    b.Navigation("AmbulanciaInsumos");
                });

            modelBuilder.Entity("Ambulancia_MIS.Dominio.Insumo", b =>
                {
                    b.Navigation("AmbulanciaInsumos");
                });
#pragma warning restore 612, 618
        }
    }
}
